[package]
name = "snmp"
version = "0.2.2"
authors = ["Hroi Sigurdsson <hroi@asdf.dk>"]
description = "SNMP client library"
license = "MIT/Apache-2.0"
repository = "https://github.com/hroi/rust-snmp"
documentation = "https://docs.rs/crate/snmp"
readme = "README.md"
keywords = ["networking", "snmp", "monitoring"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.4", features = ["udp", "time"], optional = true }

[dev-dependencies]
tokio = { version = "0.2.4", features = ["udp", "time", "macros"] }

[features]
default = ["async"]
async = ["tokio"]
